@startuml Es1
!define DARKORANGE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml


class Corso {
    - codice : Integer
    - insegnamento : String
    - cfu : Float
    - studenti : List<object>
    getStudenti()
}

class Studente {
    - nome : String
    - matricola : Integer
    - età : Integer
    - corsi : List<object>
    iscrizioneCorso()
    getCorsi()
}

Class TimeSlot {
    - numeroAula : Integer
    - oraInizio : String
    - oraFine : String
    - corso : Object
    - numeroIscritti : Integer
    prenotazione()
    iscrizioneStudenti()
    getCorso()
    getNumeroIscritti()
}

Corso "0..*" -- "1..*"Studente
TimeSlot "0..*" -- "1" Corso
TimeSlot <-- Studente

@enduml